In [40]:
import numpy as np

In [41]:
import requests
import pandas as pd

def generar_df_exel():
    """
    Obtiene datos de productos, fichas técnicas e imágenes desde la API de Exel del Norte y los combina en un DataFrame.
    
    Retorna:
    - df_exel (pd.DataFrame): DataFrame consolidado con productos, fichas técnicas e imágenes.
    """
    base_url = "https://api01.exeldelnorte.com.mx/"
    api_key = "API_6ee6a508bb7ebd80d19ef1d6edf141354cade0f7"
    
    headers = {"Authorization": api_key}
    
    # Obtener datos de productos
    try:
        response = requests.get(base_url + "productos", headers=headers, params={"sin_stock": "false"})
        response.raise_for_status()
        productos = response.json().get("datos", [])
        df_productos = pd.DataFrame(productos) if productos else pd.DataFrame()
    except requests.exceptions.RequestException as e:
        print(f"Error al obtener productos: {e}")
        return pd.DataFrame()
    
    # Obtener ficha técnica
    try:
        response = requests.get(base_url + "productos_fichatecnica", headers=headers)
        response.raise_for_status()
        tecnica = response.json().get("datos", [])
        df_tecnica = pd.DataFrame(tecnica) if tecnica else pd.DataFrame()
    except requests.exceptions.RequestException as e:
        print(f"Error al obtener ficha técnica: {e}")
        df_tecnica = pd.DataFrame()  # Si falla, seguimos sin ficha técnica
    
    # Unir productos con ficha técnica si ambas tablas tienen datos
    if not df_productos.empty and not df_tecnica.empty:
        df_exel = df_productos.merge(df_tecnica[['sku', 'ficha_tecnica']], on='sku', how='left')
    else:
        df_exel = df_productos
    
    # Obtener imágenes
    try:
        response = requests.get(base_url + "imagenes", headers=headers)
        response.raise_for_status()
        imagenes = response.json().get("DATA", [])
        df_imagenes = pd.DataFrame(imagenes) if imagenes else pd.DataFrame()
    except requests.exceptions.RequestException as e:
        print(f"Error al obtener imágenes: {e}")
        df_imagenes = pd.DataFrame()  # Si falla, seguimos sin imágenes

    # Unir imágenes si existen
    if not df_imagenes.empty:
        df_exel = df_exel.merge(df_imagenes[['sku', 'imagenes']], on='sku', how='left')

    return df_exel

In [42]:
df = generar_df_exel()

In [43]:
df

,id,referencia,sku,codigo_barras,codigo_sat,nombre,descripcion_extendida,stock,precio,precio_oferta,...,marca_id,marca_nombre,familia_id,familia_nombre,subcategoria_id,subcategoria_nombre,categoria_id,categoria_nombre,ficha_tecnica,imagenes
0,2,3MCACCAC016,WR209MB,051131980921,43211806,Descansa Muñecas 3M Negro de Espuma para Tecla...,Reposamuñecas con relleno de espuma y base ant...,1,284.065600,284.065600,...,3M,3M,ACCAC,ACCESORIOS COMPUTADORA,10,Artículos de Oficina y Mobiliario,17,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...
1,3,3MPADHAB001,6065,051141239927,31201600,Adhesivo 3M Aerosol Spray Mount 290 gr Pieza,Scotch Spray Mount™ Adhesivo en Aerosol reposi...,158,178.890400,178.890400,...,3M,3M,ADHAB,ADHESIVO,7,Cintas y Pegamentos,17,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...
2,4,3MPADHAB002,7716,051141239941,31201600,Adhesivo 3M Super 77 Aerosol 305 gr Pieza,Scotch® Super 77 Adhesivo en aerosol multiprop...,12,189.862400,189.862400,...,3M,3M,ADHAB,ADHESIVO,7,Cintas y Pegamentos,17,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...
3,6,3MPBADAB017,686L-GBR,51131945524,55121616,Banderitas 3M Adhesivas Rígidas Post-It 3M 686...,,0,NaN,NaN,...,3M,3M,BADAB,BANDERITAS,10,Artículos de Oficina y Mobiliario,17,Oficina y Escolar,NaN,NaN
4,8,3MPBADAB001,680-5,021200666971,55121616,Banderitas 3M 680 Post It Amarillo 12 Piezas c...,,0,NaN,NaN,...,3M,3M,BADAB,BANDERITAS,11,Hojas Notas y Formatos,17,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14892,34172,LNCACCAC291,4X31S04857,195892125037,43211724,Kit de Teclado y Mouse Lenovo Inalámbrico Mult...,,45,1016.126800,1016.126800,...,LN,LENOVO,ACCAC,ACCESORIOS COMPUTADORA,6,Accesorios,1,Computo,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...
14893,34177,BNCACCAH030,WDR02U,840046042905,43221700,Dongle Inalámbrico BenQ Bluetooth 4.0 Wi-Fi Co...,,4,839.768800,839.768800,...,BN,BENQ,ACCAH,ACCESORIOS VIDEOPROYECTOR,8,Accesorios,6,Cámara Video y Proyección,NaN,NaN
14894,34178,SDOMEMAB109,SDCZ410-064G-G46,619659181918,32101622,Memoria USB 64GB SanDisk Ultra Shift 3.2 Negro...,,1000,90.984400,90.984400,...,SD,SANDISK,MEMAB,MEMORIAS,3,USB,4,Almacenamiento,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...
14895,34180,SAHTALAB175,SM-X230NZSAMXO,8806097807971,43211509,"Tablet Samsung Galaxy Tab A11+ 11"" OctaCore 12...",,490,3840.262100,3840.262100,...,SA,SAMSUNG,TALAB,TABLET,7,Tablets,1,Computo,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...
14896,34187,CAIPLOAB043,6407C013AA,13803375480,43212107,Plotter Canon ImagePROGRAF Pro 4600 44 Pulgada...,,0,NaN,NaN,...,CA,CANON,PLOAB,PLOTTER,5,Plotters,2,Impresión y Multifuncionales,NaN,NaN

In [44]:
df[df['sku']=='83GW0055LM']

,id,referencia,sku,codigo_barras,codigo_sat,nombre,descripcion_extendida,stock,precio,precio_oferta,...,marca_id,marca_nombre,familia_id,familia_nombre,subcategoria_id,subcategoria_nombre,categoria_id,categoria_nombre,ficha_tecnica,imagenes
14006,31690,LNHLATAC387,83GW0055LM,199271947951,43211503,"Laptop Lenovo V15 G5 IRL 15.6"" No Táctil Intel...",,0,NaN,NaN,...,LN,LENOVO,LATAC,LAPTOP,1,Laptop,1,Computo,NaN,NaN

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14897 entries, 0 to 14896
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     14897 non-null  str
 1   referencia             14897 non-null  str
 2   sku                    14897 non-null  str
 3   codigo_barras          14897 non-null  str
 4   codigo_sat             14897 non-null  str
 5   nombre                 14897 non-null  str
 6   descripcion_extendida  14897 non-null  str
 7   stock                  14897 non-null  str
 8   precio                 9000 non-null   str
 9   precio_oferta          9000 non-null   str
 10  precio_sin_oferta      9000 non-null   str
 11  oferta                 14897 non-null  bool
 12  moneda                 14897 non-null  str
 13  marca_id               14897 non-null  str
 14  marca_nombre           14897 non-null  str
 15  familia_id             14897 non-null  str
 16  familia_nombre         14897 non-null  str
 17  subcategoria_id        14897 non-null  str
 18  subcategoria_nombre    14897 non-null  str
 19  categoria_id           14897 non-null  str
 20  categoria_nombre       14897 non-null  str
 21  ficha_tecnica          8421 non-null   object
 22  imagenes               9036 non-null   object
dtypes: bool(1), object(2), str(20)
memory usage: 2.5+ MB

In [46]:
# Columnas a eliminar según tus requerimientos
columnas_eliminar = [
    'id', 'referencia', 'marca_id', 'familia_id', 'subcategoria_id',
    'categoria_id', 'codigo_sat', 'precio_oferta', 'precio_sin_oferta',
    'familia_nombre', 'subcategoria_nombre', 
    'codigo_barras', 'oferta'
]
df.drop(columns=columnas_eliminar, errors='ignore', inplace=True)

In [47]:
# Mapeo y creación de columnas
df['clave_producto_exel'] = df['sku']
df['ID_PROVEEDOR'] = '4'

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14897 entries, 0 to 14896
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    14897 non-null  str
 1   nombre                 14897 non-null  str
 2   descripcion_extendida  14897 non-null  str
 3   stock                  14897 non-null  str
 4   precio                 9000 non-null   str
 5   moneda                 14897 non-null  str
 6   marca_nombre           14897 non-null  str
 7   categoria_nombre       14897 non-null  str
 8   ficha_tecnica          8421 non-null   object
 9   imagenes               9036 non-null   object
 10  clave_producto_exel    14897 non-null  str
 11  ID_PROVEEDOR           14897 non-null  str
dtypes: object(2), str(10)
memory usage: 1.4+ MB

In [49]:
df.sample(4)

,sku,nombre,descripcion_extendida,stock,precio,moneda,marca_nombre,categoria_nombre,ficha_tecnica,imagenes,clave_producto_exel,ID_PROVEEDOR
4231,17400110308,CORRECTOR PAPERMATE 70482 DRY LINE GRIP C/6,,94,261.423400,MXN,PAPERMATTE,Oficina y Escolar,"[{'grupo': 'Detalle tecníco', 'caracteristicas...",[https://contenidos.exel.com.mx/ImagenesProduc...,17400110308,4
8779,CRD-MC33-2SUCHG-01,Zebra Cargador 50W Negro para MC33,,0,NaN,MXN,ZEBRA,Energía y Cables,NaN,NaN,CRD-MC33-2SUCHG-01,4
250,AHM800-4TU32G1-CUSBK,"Disco duro 4TB Externo Adata HM800 3.5"" USB 3....",¡El disco duro externo ADATA HM800 y su televi...,0,NaN,MXN,ADATA,Almacenamiento,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...,AHM800-4TU32G1-CUSBK,4
58,NF3,Notas Adhesivas 3M Note fix 3.8x5.1 Color Amar...,,0,NaN,MXN,3M,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...,NF3,4

In [50]:
rename_map = {
        'sku': 'SKU',
        'nombre': 'nombre_exel',
        'stock': 'disponibilidad_exel',
        'precio': 'precio_exel',
        'moneda': 'moneda_exel',
        'marca_nombre': 'marca_exel',
        'categoria_nombre': 'categoria_exel',
        'ficha_tecnica': 'especificaciones_exel',
        'imagenes': 'imagen_exel',
        'descripcion_extendida': 'descripcion_exel'
    }
df.rename(columns=rename_map, inplace=True)

In [51]:
# Opción A: Limpiar espacios en blanco y convertir vacíos a NaN
df['descripcion_exel'] = df['descripcion_exel'].str.strip().replace('', np.nan)

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14897 entries, 0 to 14896
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SKU                    14897 non-null  str
 1   nombre_exel            14897 non-null  str
 2   descripcion_exel       3805 non-null   str
 3   disponibilidad_exel    14897 non-null  str
 4   precio_exel            9000 non-null   str
 5   moneda_exel            14897 non-null  str
 6   marca_exel             14897 non-null  str
 7   categoria_exel         14897 non-null  str
 8   especificaciones_exel  8421 non-null   object
 9   imagen_exel            9036 non-null   object
 10  clave_producto_exel    14897 non-null  str
 11  ID_PROVEEDOR           14897 non-null  str
dtypes: object(2), str(10)
memory usage: 1.4+ MB

In [55]:
df[df['descripcion_exel'].notnull()]

,SKU,nombre_exel,descripcion_exel,disponibilidad_exel,precio_exel,moneda_exel,marca_exel,categoria_exel,especificaciones_exel,imagen_exel,clave_producto_exel,ID_PROVEEDOR
0,WR209MB,Descansa Muñecas 3M Negro de Espuma para Tecla...,Reposamuñecas con relleno de espuma y base ant...,1,284.065600,MXN,3M,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...,WR209MB,4
1,6065,Adhesivo 3M Aerosol Spray Mount 290 gr Pieza,Scotch Spray Mount™ Adhesivo en Aerosol reposi...,158,178.890400,MXN,3M,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...,6065,4
2,7716,Adhesivo 3M Super 77 Aerosol 305 gr Pieza,Scotch® Super 77 Adhesivo en aerosol multiprop...,12,189.862400,MXN,3M,Oficina y Escolar,"[{'grupo': 'Características Generales:', 'cara...",[https://contenidos.exel.com.mx/ImagenesProduc...,7716,4
7,680-31,Banderitas 3M Post It Icono Signo Firme Aquí C...,Las Banderitas Post-it son señalizadores de pá...,0,NaN,MXN,3M,Oficina y Escolar,NaN,NaN,680-31,4
8,683-5CF0,Banderitas 3M Mini 5 Colores C/100 Hojas C/6,Las Banderitas Post-it son ideales para separa...,0,NaN,MXN,3M,Oficina y Escolar,NaN,NaN,683-5CF0,4
...,...,...,...,...,...,...,...,...,...,...,...,...
13413,OM900ATLCD,UPS CyberPower 900VA Regulador Voltaje AVR Torre,CyberPower OM900ATLCD garantiza la protección ...,39,1895.602800,MXN,CYBERPOWER,Energía y Cables,"[{'grupo': 'Especificaciones Generales', 'car...",[https://contenidos.exel.com.mx/ImagenesProduc...,OM900ATLCD,4
13414,OR1500LCDRT2U,UPS CYBERPOWER OR1500,La familia Smart App LCD Inteligente es ideal ...,1,9203.485200,MXN,CYBERPOWER,Energía y Cables,"[{'grupo': 'Especificaciones Generales', 'car...",[https://contenidos.exel.com.mx/ImagenesProduc...,OR1500LCDRT2U,4
13415,OR2200LCDRT2U,UPS Cyberpower Tecnología bypass GreenPower UP...,CyberPower OR2200LCDRT2U es un UPS interactivo...,0,NaN,MXN,CYBERPOWER,Energía y Cables,"[{'grupo': 'Especificaciones Generales', 'car...",[https://contenidos.exel.com.mx/ImagenesProduc...,OR2200LCDRT2U,4
13416,AVRG900LCD,UPS CYBERPOWER 900VA / 480W CON REGULADOR AUTO...,CyberPower AVRG900LCD garantiza protección de ...,0,NaN,MXN,CYBERPOWER,Energía y Cables,NaN,NaN,AVRG900LCD,4
13418,UT750GU,UPS Cyberpower 750VA Regulador Voltaje AVR Tip...,CyberPower UT750GU garantiza la protección de ...,94,1213.186000,MXN,CYBERPOWER,Energía y Cables,"[{'grupo': 'Especificaciones Generales', 'car...",[https://contenidos.exel.com.mx/ImagenesProduc...,UT750GU,4

In [56]:
mask = df['descripcion_exel'].isna()
df.loc[mask, 'descripcion_exel'] = df.loc[mask, 'nombre_exel']

In [6]:
import requests

url = "https://api01.exeldelnorte.com.mx/imagenes?clave_producto=3MPBADAB005"

payload={}
headers = {
  'Authorization': 'API_6ee6a508bb7ebd80d19ef1d6edf141354cade0f7'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

{"DATA":[{"referencia":"3MCACCAC016","sku":"WR209MB","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MCACCAC016_zoom.jpg"]},{"referencia":"3MPADHAB001","sku":"6065","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPADHAB001_zoom.jpg"]},{"referencia":"3MPADHAB002","sku":"7716","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPADHAB002_zoom.jpg"]},{"referencia":"3MPBADAB001","sku":"680-5","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPBADAB001_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPBADAB001_2_zoom.jpg"]},{"referencia":"3MPBADAB013","sku":"671-4AU","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB013_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB013_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB013_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB013_5_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB013_zoom.jpg"]},{"referencia":"3MPBADAB019","sku":"686-ALOPRYT","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB019_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB019_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB019_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPBADAB019_4_zoom.jpg"]},{"referencia":"3MPCINAB002","sku":"8101833","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB002_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB002_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB002_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB002_5_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB002_6_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB002_zoom.jpg"]},{"referencia":"3MPCINAB004","sku":"8101865","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB004_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB004_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB004_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB004_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB004_5_zoom.jpg"]},{"referencia":"3MPCINAB005","sku":"8102465","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB005_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB005_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB005_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB005_5_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB005_zoom.jpg"]},{"referencia":"3MPCINAB013","sku":"8455013","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB013_zoom.jpg"]},{"referencia":"3MPCINAB014","sku":"8453813","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB014_zoom.jpg"]},{"referencia":"3MPCINAB016","sku":"8101812D","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB016_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB016_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB016_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB016_4_zoom.jpg"]},{"referencia":"3MPCINAB018","sku":"8101233","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB018_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB018_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB018_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB018_5_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB018_zoom.jpg"]},{"referencia":"3MPCINAB020","sku":"136D","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB020_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB020_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB020_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB020_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB020_5_zoom.jpg"]},{"referencia":"3MPCINAB024","sku":"8103","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB024_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB024_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB024_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB024_zoom.jpg"]},{"referencia":"3MPCINAB027","sku":"5501833D","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB027_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB027_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB027_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB027_4_zoom.jpg"]},{"referencia":"3MPCINAB028","sku":"665","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB028_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB028_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB028_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB028_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB028_5_zoom.jpg"]},{"referencia":"3MPCINAB033","sku":"5081210","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPCINAB033_zoom.jpg"]},{"referencia":"3MPCINAB035","sku":"5082466","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPCINAB035_zoom.jpg"]},{"referencia":"3MPCINAB036","sku":"5081233","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPCINAB036_zoom.jpg"]},{"referencia":"3MPCINAB038","sku":"1050","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB038_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB038_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB038_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB038_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB038_5_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAB038_6_zoom.jpg"]},{"referencia":"3MPCINAB040","sku":"5081266","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPCINAB040_zoom.jpg"]},{"referencia":"3MPCINAB041","sku":"5081825","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPCINAB041_zoom.jpg"]},{"referencia":"3MPCINAC006","sku":"MC500000856","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAC006_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAC006_2_zoom.jpg"]},{"referencia":"3MPCINAF005","sku":"5501833","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF005_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF005_2_zoom.jpg"]},{"referencia":"3MPCINAF006","sku":"5501865","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF006_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF006_2_zoom.jpg"]},{"referencia":"3MPCINAF007","sku":"5502465","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF007_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF007_zoom.jpg"]},{"referencia":"3MPCINAF013","sku":"70016046701","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF013_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF013_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF013_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF013_zoom.jpg"]},{"referencia":"3MPCINAF017","sku":"MC500000914","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF017_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPCINAF017_2_zoom.jpg"]},{"referencia":"3MPDEPAB004","sku":"C-38","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPDEPAB004_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPDEPAB004_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPDEPAB004_3_zoom.jpg"]},{"referencia":"3MPDEPAB021","sku":"DS100","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPDEPAB021_zoom.jpg"]},{"referencia":"3MPLIMAB001","sku":"MC900170002","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB001_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB001_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB001_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB001_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB001_5_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB001_6_zoom.jpg"]},{"referencia":"3MPLIMAB002","sku":"MC900174244","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPLIMAB002_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPLIMAB002_2_zoom.jpg"]},{"referencia":"3MPLIMAB003","sku":"UU004637128","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB003_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB003_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB003_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB003_4_zoom.jpg"]},{"referencia":"3MPLIMAB004","sku":"MN900170841","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB004_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB004_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB004_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPLIMAB004_4_zoom.jpg"]},{"referencia":"3MPLIMAB006","sku":"MC900175795","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPLIMAB006_zoom.jpg"]},{"referencia":"3MPPOSAB039","sku":"653-4 AF","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB039_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB039_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB039_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB039_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB039_5_zoom.jpg"]},{"referencia":"3MPPOSAB001","sku":"2018-LA","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB001_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB001_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB001_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB001_zoom.jpg"]},{"referencia":"3MPPOSAB003","sku":"70007052692","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB003_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB003_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB003_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB003_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB003_5_zoom.jpg"]},{"referencia":"3MPPOSAB005","sku":"654","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB005_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB005_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB005_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB005_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB005_5_zoom.jpg"]},{"referencia":"3MPPOSAB009","sku":"660","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB009_zoom.jpg"]},{"referencia":"3MPPOSAB012","sku":"NF3","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3MPPOSAB012_zoom.jpg"]},{"referencia":"3MPPOSAB021","sku":"NF4-N","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB021_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB021_2_zoom.jpg"]},{"referencia":"3MPPOSAB031","sku":"2072","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB031_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB031_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB031_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB031_4_zoom.jpg"]},{"referencia":"3MPPOSAB032","sku":"654-5UC","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB032_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB032_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB032_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB032_zoom.jpg"]},{"referencia":"3MPPOSAB041","sku":"654-2","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB041_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB041_2_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB041_3_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB041_4_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB041_5_zoom.jpg"]},{"referencia":"3MPPOSAB046","sku":"654-5SSW","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPPOSAB046_zoom.jpg"]},{"referencia":"3MPSEPAB001","sku":"670-5AF","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPSEPAB001_zoom.jpg"]},{"referencia":"3MPTIJAB001","sku":"1426","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPTIJAB001_zoom.jpg"]},{"referencia":"3MPTIJAB002","sku":"1427","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPTIJAB002_zoom.jpg"]},{"referencia":"3MPTIJAB003","sku":"1428","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPTIJAB003_zoom.jpg"]},{"referencia":"3MPTIJAB004","sku":"70007073656","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/3M\/3MPTIJAB004_zoom.jpg"]},{"referencia":"ACPBROAB002","sku":"P1580","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPBROAB002_zoom.jpg"]},{"referencia":"ACPCARAB005","sku":"P0943","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB005_zoom.jpg"]},{"referencia":"ACPCARAB009","sku":"P4554","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB009_zoom.jpg"]},{"referencia":"ACPCARAB010","sku":"P4552","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB010_zoom.jpg"]},{"referencia":"ACPCARAB011","sku":"P4553","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB011_zoom.jpg"]},{"referencia":"ACPCARAB012","sku":"P4563","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB012_zoom.jpg"]},{"referencia":"ACPCARAB013","sku":"P4564","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB013_zoom.jpg"]},{"referencia":"ACPCARAB014","sku":"P4565","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB014_zoom.jpg"]},{"referencia":"ACPCARAB015","sku":"P4555","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB015_zoom.jpg"]},{"referencia":"ACPCARAB016","sku":"P4557","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB016_zoom.jpg"]},{"referencia":"ACPCARAB017","sku":"P4558","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB017_zoom.jpg"]},{"referencia":"ACPCARAB021","sku":"P0963","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB021_zoom.jpg"]},{"referencia":"ACPCARAB037","sku":"P0139","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/P0139_zoom.jpg"]},{"referencia":"ACPCARAB050","sku":"P1602","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB050_zoom.jpg"]},{"referencia":"ACPCARAB053","sku":"P0234","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB053_zoom.jpg"]},{"referencia":"ACPCARAB056","sku":"P0245","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB056_zoom.jpg"]},{"referencia":"ACPCARAB057","sku":"P0246","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB057_zoom.jpg"]},{"referencia":"ACPCARAB059","sku":"P0248","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB059_zoom.jpg"]},{"referencia":"ACPCARAB064","sku":"P2311","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB064_zoom.jpg"]},{"referencia":"ACPCARAB065","sku":"P2318","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB065_zoom.jpg","https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB065_2_zoom.jpg"]},{"referencia":"ACPCARAB066","sku":"P4778","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB066_zoom.jpg"]},{"referencia":"ACPCARAB067","sku":"P3129","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB067_zoom.jpg"]},{"referencia":"ACPCARAB069","sku":"P7147","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB069_zoom.jpg"]},{"referencia":"ACPCARAB071","sku":"P7148","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB071_zoom.jpg"]},{"referencia":"ACPCARAB073","sku":"P7149","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB073_zoom.jpg"]},{"referencia":"ACPCARAB075","sku":"P4397","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB075_zoom.jpg"]},{"referencia":"ACPCARAB088","sku":"P3213","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB088_zoom.jpg"]},{"referencia":"ACPCARAB090","sku":"P4569","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB090_zoom.jpg"]},{"referencia":"ACPCARAB093","sku":"P0843","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB093_zoom.jpg"]},{"referencia":"ACPCARAB094","sku":"P3140","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB094_zoom.jpg"]},{"referencia":"ACPCARAB096","sku":"P4566","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB096_zoom.jpg"]},{"referencia":"ACPCARAB097","sku":"P4568","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB097_zoom.jpg"]},{"referencia":"ACPCARAB114","sku":"P1111","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB114_zoom.jpg"]},{"referencia":"ACPCARAB130","sku":"P3636","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB130_zoom.jpg"]},{"referencia":"ACPCARAB131","sku":"P3631","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/ACPCARAB131_zoom.jpg"]},{"referencia":"ACPCARAB132","sku":"P1192","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB132_zoom.jpg"]},{"referencia":"ACPCARAB133","sku":"P1195","imagenes":["https:\/\/contenidos.exel.com.mx\/ImagenesProductos\/AC\/ACPCARAB133_zoom.jpg"]},{"referencia":"ACPCARAB135","sku":"P1250 PAQ 12","imagenes":["https:\

In [2]:
pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\moiseseugenionavamar\github\excel-del-norte\.venv\lib\site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 320.0 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 405.7 kB/s eta 0:00:00
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB 8.6 MB/s eta 0:00:05
   - -------------------------------------- 1.6/36.6 MB 20.3 MB/s eta 0:00:02
   ---- ----------------------------------- 3.9/36.6 MB 31.5 MB/s eta 0:00:02
   ------ --------------------------------- 6.3/36.6 MB 36.9 MB/s eta 0:00:01
   ---------- ----------------------------- 9.4/36.6 MB 42.8 MB/s eta 0:00:01
   ------------ --------------------------- 11.3/36.6 MB 50.1 MB/s eta 0:00:01
   ------------- -------------------------- 12.7/36.6 MB 50.4 MB/s eta 0:00:01
   --------------- ------------------------ 13.8/36.6 MB 43.7 MB/s eta 0:00:01
   --------------- ------------------------ 14.5/36.6 MB 38.6 MB/s eta 0:00:01
   ---------------- ----------------------- 15.4/36.6 MB 32.7 MB/s eta 0:00:01
   ----------------- ---------------------- 16.4/36.6 MB 31.2 MB/s eta 0:00:01
   ------------------ --------------------- 17.3/36.6 MB 28.4 MB/s eta 0:00:01
   -------------------- ------------------- 18.4/36.6 MB 27.3 MB/s eta 0:00:01
   --------------------- ------------------ 19.4/36.6 MB 25.2 MB/s eta 0:00:01
   ---------------------- ----------------- 20.1/36.6 MB 23.4 MB/s eta 0:00:01
   ----------------------- ---------------- 21.1/36.6 MB 21.8 MB/s eta 0:00:01
   ------------------------ --------------- 22.0/36.6 MB 21.1 MB/s eta 0:00:01
   ------------------------- -------------- 23.1/36.6 MB 21.1 MB/s eta 0:00:01
   -------------------------- ------------- 24.2/36.6 MB 21.1 MB/s eta 0:00:01
   --------------------------- ------------ 25.1/36.6 MB 21.8 MB/s eta 0:00:01
   ---------------------------- ----------- 25.8/36.6 MB 21.1 MB/s eta 0:00:01
   ----------------------------- ---------- 26.9/36.6 MB 21.1 MB/s eta 0:00:01
   ------------------------------ --------- 28.0/36.6 MB 21.8 MB/s eta 0:00:01
   -------------------------------- ------- 29.4/36.6 MB 22.6 MB/s eta 0:00:01
   --------------------------------- ------ 30.4/36.6 MB 23.4 MB/s eta 0:00:01
   ---------------------------------- ----- 31.5/36.6 MB 23.4 MB/s eta 0:00:01
   ----------------------------------- ---- 32.6/36.6 MB 25.2 MB/s eta 0:00:01
   ------------------------------------- -- 34.0/36.6 MB 24.2 MB/s eta 0:00:01
   -------------------------------------- - 35.0/36.6 MB 25.2 MB/s eta 0:00:01
   -------------------------------------- - 35.6/36.6 MB 24.2 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 23.4 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 14.9 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
response.text

'{"DATA":[{"referencia":"3MCACCAC016","sku":"WR209MB","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MCACCAC016_zoom.jpg"]},{"referencia":"3MPADHAB001","sku":"6065","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPADHAB001_zoom.jpg"]},{"referencia":"3MPADHAB002","sku":"7716","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPADHAB002_zoom.jpg"]},{"referencia":"3MPBADAB001","sku":"680-5","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPBADAB001_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPBADAB001_2_zoom.jpg"]},{"referencia":"3MPBADAB013","sku":"671-4AU","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB013_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB013_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB013_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB013_5_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB013_zoom.jpg"]},{"referencia":"3MPBADAB019","sku":"686-ALOPRYT","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB019_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB019_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB019_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPBADAB019_4_zoom.jpg"]},{"referencia":"3MPCINAB002","sku":"8101833","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB002_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB002_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB002_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB002_5_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB002_6_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB002_zoom.jpg"]},{"referencia":"3MPCINAB004","sku":"8101865","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB004_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB004_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB004_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB004_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB004_5_zoom.jpg"]},{"referencia":"3MPCINAB005","sku":"8102465","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB005_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB005_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB005_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB005_5_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB005_zoom.jpg"]},{"referencia":"3MPCINAB013","sku":"8455013","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB013_zoom.jpg"]},{"referencia":"3MPCINAB014","sku":"8453813","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB014_zoom.jpg"]},{"referencia":"3MPCINAB016","sku":"8101812D","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB016_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB016_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB016_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB016_4_zoom.jpg"]},{"referencia":"3MPCINAB018","sku":"8101233","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB018_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB018_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB018_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB018_5_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB018_zoom.jpg"]},{"referencia":"3MPCINAB020","sku":"136D","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB020_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB020_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB020_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB020_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB020_5_zoom.jpg"]},{"referencia":"3MPCINAB024","sku":"8103","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB024_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB024_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB024_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB024_zoom.jpg"]},{"referencia":"3MPCINAB027","sku":"5501833D","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB027_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB027_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB027_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB027_4_zoom.jpg"]},{"referencia":"3MPCINAB028","sku":"665","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB028_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB028_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB028_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB028_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB028_5_zoom.jpg"]},{"referencia":"3MPCINAB033","sku":"5081210","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPCINAB033_zoom.jpg"]},{"referencia":"3MPCINAB035","sku":"5082466","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPCINAB035_zoom.jpg"]},{"referencia":"3MPCINAB036","sku":"5081233","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPCINAB036_zoom.jpg"]},{"referencia":"3MPCINAB038","sku":"1050","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB038_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB038_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB038_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB038_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB038_5_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAB038_6_zoom.jpg"]},{"referencia":"3MPCINAB040","sku":"5081266","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPCINAB040_zoom.jpg"]},{"referencia":"3MPCINAB041","sku":"5081825","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPCINAB041_zoom.jpg"]},{"referencia":"3MPCINAC006","sku":"MC500000856","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAC006_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAC006_2_zoom.jpg"]},{"referencia":"3MPCINAF005","sku":"5501833","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF005_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF005_2_zoom.jpg"]},{"referencia":"3MPCINAF006","sku":"5501865","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF006_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF006_2_zoom.jpg"]},{"referencia":"3MPCINAF007","sku":"5502465","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF007_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF007_zoom.jpg"]},{"referencia":"3MPCINAF013","sku":"70016046701","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF013_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF013_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF013_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF013_zoom.jpg"]},{"referencia":"3MPCINAF017","sku":"MC500000914","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF017_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPCINAF017_2_zoom.jpg"]},{"referencia":"3MPDEPAB004","sku":"C-38","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPDEPAB004_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPDEPAB004_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPDEPAB004_3_zoom.jpg"]},{"referencia":"3MPDEPAB021","sku":"DS100","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPDEPAB021_zoom.jpg"]},{"referencia":"3MPLIMAB001","sku":"MC900170002","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB001_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB001_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB001_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB001_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB001_5_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB001_6_zoom.jpg"]},{"referencia":"3MPLIMAB002","sku":"MC900174244","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPLIMAB002_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPLIMAB002_2_zoom.jpg"]},{"referencia":"3MPLIMAB003","sku":"UU004637128","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB003_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB003_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB003_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB003_4_zoom.jpg"]},{"referencia":"3MPLIMAB004","sku":"MN900170841","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB004_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB004_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB004_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPLIMAB004_4_zoom.jpg"]},{"referencia":"3MPLIMAB006","sku":"MC900175795","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPLIMAB006_zoom.jpg"]},{"referencia":"3MPPOSAB039","sku":"653-4 AF","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB039_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB039_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB039_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB039_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB039_5_zoom.jpg"]},{"referencia":"3MPPOSAB001","sku":"2018-LA","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB001_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB001_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB001_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB001_zoom.jpg"]},{"referencia":"3MPPOSAB003","sku":"70007052692","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB003_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB003_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB003_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB003_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB003_5_zoom.jpg"]},{"referencia":"3MPPOSAB005","sku":"654","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB005_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB005_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB005_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB005_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB005_5_zoom.jpg"]},{"referencia":"3MPPOSAB009","sku":"660","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB009_zoom.jpg"]},{"referencia":"3MPPOSAB012","sku":"NF3","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3MPPOSAB012_zoom.jpg"]},{"referencia":"3MPPOSAB021","sku":"NF4-N","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB021_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB021_2_zoom.jpg"]},{"referencia":"3MPPOSAB031","sku":"2072","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB031_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB031_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB031_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB031_4_zoom.jpg"]},{"referencia":"3MPPOSAB032","sku":"654-5UC","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB032_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB032_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB032_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB032_zoom.jpg"]},{"referencia":"3MPPOSAB041","sku":"654-2","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB041_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB041_2_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB041_3_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB041_4_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB041_5_zoom.jpg"]},{"referencia":"3MPPOSAB046","sku":"654-5SSW","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPPOSAB046_zoom.jpg"]},{"referencia":"3MPSEPAB001","sku":"670-5AF","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPSEPAB001_zoom.jpg"]},{"referencia":"3MPTIJAB001","sku":"1426","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPTIJAB001_zoom.jpg"]},{"referencia":"3MPTIJAB002","sku":"1427","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPTIJAB002_zoom.jpg"]},{"referencia":"3MPTIJAB003","sku":"1428","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPTIJAB003_zoom.jpg"]},{"referencia":"3MPTIJAB004","sku":"70007073656","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/3M\\/3MPTIJAB004_zoom.jpg"]},{"referencia":"ACPBROAB002","sku":"P1580","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPBROAB002_zoom.jpg"]},{"referencia":"ACPCARAB005","sku":"P0943","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB005_zoom.jpg"]},{"referencia":"ACPCARAB009","sku":"P4554","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB009_zoom.jpg"]},{"referencia":"ACPCARAB010","sku":"P4552","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB010_zoom.jpg"]},{"referencia":"ACPCARAB011","sku":"P4553","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB011_zoom.jpg"]},{"referencia":"ACPCARAB012","sku":"P4563","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB012_zoom.jpg"]},{"referencia":"ACPCARAB013","sku":"P4564","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB013_zoom.jpg"]},{"referencia":"ACPCARAB014","sku":"P4565","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB014_zoom.jpg"]},{"referencia":"ACPCARAB015","sku":"P4555","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB015_zoom.jpg"]},{"referencia":"ACPCARAB016","sku":"P4557","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB016_zoom.jpg"]},{"referencia":"ACPCARAB017","sku":"P4558","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB017_zoom.jpg"]},{"referencia":"ACPCARAB021","sku":"P0963","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB021_zoom.jpg"]},{"referencia":"ACPCARAB037","sku":"P0139","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/P0139_zoom.jpg"]},{"referencia":"ACPCARAB050","sku":"P1602","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB050_zoom.jpg"]},{"referencia":"ACPCARAB053","sku":"P0234","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB053_zoom.jpg"]},{"referencia":"ACPCARAB056","sku":"P0245","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB056_zoom.jpg"]},{"referencia":"ACPCARAB057","sku":"P0246","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB057_zoom.jpg"]},{"referencia":"ACPCARAB059","sku":"P0248","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB059_zoom.jpg"]},{"referencia":"ACPCARAB064","sku":"P2311","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB064_zoom.jpg"]},{"referencia":"ACPCARAB065","sku":"P2318","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB065_zoom.jpg","https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB065_2_zoom.jpg"]},{"referencia":"ACPCARAB066","sku":"P4778","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/AC\\/ACPCARAB066_zoom.jpg"]},{"referencia":"ACPCARAB067","sku":"P3129","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB067_zoom.jpg"]},{"referencia":"ACPCARAB069","sku":"P7147","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB069_zoom.jpg"]},{"referencia":"ACPCARAB071","sku":"P7148","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB071_zoom.jpg"]},{"referencia":"ACPCARAB073","sku":"P7149","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB073_zoom.jpg"]},{"referencia":"ACPCARAB075","sku":"P4397","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB075_zoom.jpg"]},{"referencia":"ACPCARAB088","sku":"P3213","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB088_zoom.jpg"]},{"referencia":"ACPCARAB090","sku":"P4569","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB090_zoom.jpg"]},{"referencia":"ACPCARAB093","sku":"P0843","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB093_zoom.jpg"]},{"referencia":"ACPCARAB094","sku":"P3140","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB094_zoom.jpg"]},{"referencia":"ACPCARAB096","sku":"P4566","imagenes":["https:\\/\\/contenidos.exel.com.mx\\/ImagenesProductos\\/ACPCARAB096_zoom.jpg"]},{"re